services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${BOT_NAME}
    restart: always
    volumes:
      - data:/app/data:rw
      - ./.env:/app/.env:ro
volumes:
  data:
